services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StefanFroemken\ExtKickstarter\:
    resource: '../Classes/*'
    exclude:
    - '../Classes/Domain/Model/*'

  StefanFroemken\ExtKickstarter\Service\BuildExtensionService:
    arguments:
      $builders: !tagged_iterator { tag: 'ext-kickstarter.builder' }
